version: '3'

services:
  neo4j:
    build:
      context: .
      dockerfile: ./neo4j/Dockerfile
    container_name: neo4j-playground
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science", "n10s"]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
    networks:
      - playground-network

  jupyter-lab:
    build:
      context: .
      dockerfile: ./jupyter-lab/Dockerfile
    container_name: jupyter-lab-playground
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter-lab/notebooks:/playground/notebooks
    links:
      - neo4j
    networks:
      - playground-network

networks:
  playground-network: