name: kd-playground
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - pip:
      - py2neo
      - neo4j
