WITH '
@prefix : <http://prismstandard.org/namespaces/basic/2.0/> .
@prefix a1: <http://www.elsevier.com/xml/schema/grant/grant-1.1> .
@prefix a2: <http://www.elsevier.com/xml/schema/grant/grant-1.2> .
@prefix arg: <http://spinrdf.org/arg#> .
@prefix bam: <http://www.elsevier.com/xml/schema/rdf/BasicAssetMetadata-1/> .
@prefix dash: <http://datashapes.org/dash#> .
@prefix dcam: <http://purl.org/dc/dcam/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix ebs: <http://www.elsevier.com/xml/schema/rdf/EMMeTBasicSatellite-1/> .
@prefix ecm: <http://www.elsevier.com/xml/schema/rdf/common/Metadata-1/> .
@prefix edg: <http://edg.topbraid.solutions/model/> .
@prefix edm: <https://data.elsevier.com/schema/edm/> .
@prefix egm: <http://www.elsevier.com/xml/schema/rdf/ElsevierGenericMembershipSatellite-1/> .
@prefix egq: <http://www.elsevier.com/xml/schema/rdf/ElsevierGenericSequenceSatellite-1/> .
@prefix egv: <http://www.elsevier.com/xml/schema/rdf/ElsevierGenericVocabularySatellite-1/> .
@prefix emloc: <http://data.elsevier.com/vocabulary/EMMeT/locrel/> .
@prefix emst: <http://www.elsevier.com/xml/schema/rdf/EGVSatelliteTagging-1/> .
@prefix epr: <http://www.elsevier.com/xml/schema/rdf/EMMeTProvenanceSatellite-1/> .
@prefix eum: <https://data.elsevier.com/schema/unitsOfMeasure/> .
@prefix evo: <https://data.elsevier.com/schema/evo/> .
@prefix geo-ont: <http://www.geonames.org/ontology#> .
@prefix graphql: <http://datashapes.org/graphql#> .
@prefix idm: <https://data.elsevier.com/schema/idm/> .
@prefix idtype: <https://data.elsevier.com/e/identifier/> .
@prefix knovel_properties_vocabulary: <https://data.elsevier.com/engineering/knovel/properties/schema/> .
@prefix knovelproperties: <http://data.elsevier.com/vocabulary/knovel/properties/> .
@prefix metadata: <http://topbraid.org/metadata#> .
@prefix oa: <http://www.w3.org/ns/oa#> .
@prefix omniscienceextensionmerged_02052019: <http://data.elsevier.com/vocabulary/OmniScienceExtension/> .
@prefix os: <http://data.elsevier.com/vocabulary/OmniScience/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix pav: <http://purl.org/swan/pav/provenance/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix provenance_authoring_and_versioning_ontology: <http://purl.org/pav/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rv: <https://data.elsevier.com/research/schema/rv/> .
@prefix s: <http://states.data/> .
@prefix sat: <http://www.elsevier.com/xml/schema/rdf/LDR-Satellites/Base-1/> .
@prefix schema: <https://none.schema.org/> .
@prefix semrel: <http://data.elsevier.com/EMMeT/SemRelations/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix skm: <http://synaptica.net/skm/> .
@prefix skmse: <http://synaptica.net/skm/subElement/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix skos_inferences: <urn:x-evn-master:skos_inferences/> .
@prefix skosshapes: <http://topbraid.org/skos.shapes#> .
@prefix skosxl: <http://www.w3.org/2008/05/skos-xl#> .
@prefix smf: <http://topbraid.org/sparqlmotionfunctions#> .
@prefix sp: <http://spinrdf.org/sp#> .
@prefix spin: <http://spinrdf.org/spin#> .
@prefix spl: <http://spinrdf.org/spl#> .
@prefix svf: <http://www.elsevier.com/xml/schema/grant/grant-1.2/> .
@prefix swa: <http://topbraid.org/swa#> .
@prefix tag: <http://www.elsevier.com/xml/schema/rdf/LDR-Satellites/TagAnnot-1/> .
@prefix teamwork: <http://topbraid.org/teamwork#> .
@prefix teamworkconstraints: <http://topbraid.org/teamworkconstraints#> .
@prefix tosh: <http://topbraid.org/tosh#> .
@prefix vann: <http://purl.org/vocab/vann/> .
@prefix void: <http://rdfs.org/ns/void#> .
@prefix wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix xsi: <http://www.w3.org/2001/XMLSchema-instance> .
@prefix zthes: <http://synaptica.net/zthes/> .
' AS prefixes
CALL n10s.nsprefixes.addFromText(prefixes)
YIELD prefix, namespace
RETURN prefix, namespace